<?php

use App\Events\MessageSent;
use App\Http\Controllers\Admin\ServiceAreaController;
use App\Http\Controllers\WebhookLogController;
use App\Http\Middleware\JsonRequestMiddleware;
use App\Models\Category;
use App\Models\ChatMessage;
use App\Models\Order;
use App\Models\Property;
use App\Models\User;
use Illuminate\Foundation\Http\Middleware\VerifyCsrfToken;
use Illuminate\Support\Facades\Route;
use Spatie\Permission\Models\Role;



Route::get('g', function () {

    $categories = json_decode('[
        {
          "svc_id": "649",
          "svc_scat_id": "1",
          "svc_description": "Burning & Small Smoke",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "1",
          "scat_category": "Electrical & Power Systems",
          "scat_icon": "aswby1587325294067.png",
          "scat_is_general": "0",
          "scat_service_area_id": "1",
          "scat_sort": "1"
        },
        {
          "svc_id": "653",
          "svc_scat_id": "1",
          "svc_description": "Circuit Breakers",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "1",
          "scat_category": "Electrical & Power Systems",
          "scat_icon": "aswby1587325294067.png",
          "scat_is_general": "0",
          "scat_service_area_id": "1",
          "scat_sort": "1"
        },
        {
          "svc_id": "576",
          "svc_scat_id": "1",
          "svc_description": "Electrical  Fittings",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "1",
          "scat_category": "Electrical & Power Systems",
          "scat_icon": "aswby1587325294067.png",
          "scat_is_general": "0",
          "scat_service_area_id": "1",
          "scat_sort": "1"
        },
        {
          "svc_id": "155",
          "svc_scat_id": "1",
          "svc_description": "Fluctuating Power",
          "svc_code": "MTN-EL009",
          "svc_sort": "0",
          "scat_id": "1",
          "scat_category": "Electrical & Power Systems",
          "scat_icon": "aswby1587325294067.png",
          "scat_is_general": "0",
          "scat_service_area_id": "1",
          "scat_sort": "1"
        },
        {
          "svc_id": "499",
          "svc_scat_id": "1",
          "svc_description": "Generator Maintenance",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "1",
          "scat_category": "Electrical & Power Systems",
          "scat_icon": "aswby1587325294067.png",
          "scat_is_general": "0",
          "scat_service_area_id": "1",
          "scat_sort": "1"
        },
        {
          "svc_id": "650",
          "svc_scat_id": "1",
          "svc_description": "Lights",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "1",
          "scat_category": "Electrical & Power Systems",
          "scat_icon": "aswby1587325294067.png",
          "scat_is_general": "0",
          "scat_service_area_id": "1",
          "scat_sort": "1"
        },
        {
          "svc_id": "2",
          "svc_scat_id": "1",
          "svc_description": "Loss of Power",
          "svc_code": "ELECT002",
          "svc_sort": "0",
          "scat_id": "1",
          "scat_category": "Electrical & Power Systems",
          "scat_icon": "aswby1587325294067.png",
          "scat_is_general": "0",
          "scat_service_area_id": "1",
          "scat_sort": "1"
        },
        {
          "svc_id": "654",
          "svc_scat_id": "1",
          "svc_description": "Panel & Fuse Box",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "1",
          "scat_category": "Electrical & Power Systems",
          "scat_icon": "aswby1587325294067.png",
          "scat_is_general": "0",
          "scat_service_area_id": "1",
          "scat_sort": "1"
        },
        {
          "svc_id": "656",
          "svc_scat_id": "1",
          "svc_description": "Smoke Detectors",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "1",
          "scat_category": "Electrical & Power Systems",
          "scat_icon": "aswby1587325294067.png",
          "scat_is_general": "0",
          "scat_service_area_id": "1",
          "scat_sort": "1"
        },
        {
          "svc_id": "652",
          "svc_scat_id": "1",
          "svc_description": "Socket Outlets",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "1",
          "scat_category": "Electrical & Power Systems",
          "scat_icon": "aswby1587325294067.png",
          "scat_is_general": "0",
          "scat_service_area_id": "1",
          "scat_sort": "1"
        },
        {
          "svc_id": "141",
          "svc_scat_id": "1",
          "svc_description": "Sparks & Popping bonds",
          "svc_code": "ELEC-004",
          "svc_sort": "0",
          "scat_id": "1",
          "scat_category": "Electrical & Power Systems",
          "scat_icon": "aswby1587325294067.png",
          "scat_is_general": "0",
          "scat_service_area_id": "1",
          "scat_sort": "1"
        },
        {
          "svc_id": "651",
          "svc_scat_id": "1",
          "svc_description": "Switches",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "1",
          "scat_category": "Electrical & Power Systems",
          "scat_icon": "aswby1587325294067.png",
          "scat_is_general": "0",
          "scat_service_area_id": "1",
          "scat_sort": "1"
        },
        {
          "svc_id": "655",
          "svc_scat_id": "1",
          "svc_description": "Wiring",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "1",
          "scat_category": "Electrical & Power Systems",
          "scat_icon": "aswby1587325294067.png",
          "scat_is_general": "0",
          "scat_service_area_id": "1",
          "scat_sort": "1"
        },
        {
          "svc_id": "436",
          "svc_scat_id": "1",
          "svc_description": "Others",
          "svc_code": null,
          "svc_sort": "1",
          "scat_id": "1",
          "scat_category": "Electrical & Power Systems",
          "scat_icon": "aswby1587325294067.png",
          "scat_is_general": "0",
          "scat_service_area_id": "1",
          "scat_sort": "1"
        },
        {
          "svc_id": "474",
          "svc_scat_id": "2",
          "svc_description": "Blocked Drains",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "2",
          "scat_category": "Plumbing, Water & Sewage",
          "scat_icon": "i82fb1587325327961.png",
          "scat_is_general": "0",
          "scat_service_area_id": "1",
          "scat_sort": "2"
        },
        {
          "svc_id": "665",
          "svc_scat_id": "2",
          "svc_description": "Borehole",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "2",
          "scat_category": "Plumbing, Water & Sewage",
          "scat_icon": "i82fb1587325327961.png",
          "scat_is_general": "0",
          "scat_service_area_id": "1",
          "scat_sort": "2"
        },
        {
          "svc_id": "389",
          "svc_scat_id": "2",
          "svc_description": "Burst / Leaking Pipes",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "2",
          "scat_category": "Plumbing, Water & Sewage",
          "scat_icon": "i82fb1587325327961.png",
          "scat_is_general": "0",
          "scat_service_area_id": "1",
          "scat_sort": "2"
        },
        {
          "svc_id": "659",
          "svc_scat_id": "2",
          "svc_description": "Dishwasher",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "2",
          "scat_category": "Plumbing, Water & Sewage",
          "scat_icon": "i82fb1587325327961.png",
          "scat_is_general": "0",
          "scat_service_area_id": "1",
          "scat_sort": "2"
        },
        {
          "svc_id": "664",
          "svc_scat_id": "2",
          "svc_description": "Garden  Sprinkler",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "2",
          "scat_category": "Plumbing, Water & Sewage",
          "scat_icon": "i82fb1587325327961.png",
          "scat_is_general": "0",
          "scat_service_area_id": "1",
          "scat_sort": "2"
        },
        {
          "svc_id": "297",
          "svc_scat_id": "2",
          "svc_description": "Low / High Water Pressure",
          "svc_code": "MTN-PL005",
          "svc_sort": "0",
          "scat_id": "2",
          "scat_category": "Plumbing, Water & Sewage",
          "scat_icon": "i82fb1587325327961.png",
          "scat_is_general": "0",
          "scat_service_area_id": "1",
          "scat_sort": "2"
        },
        {
          "svc_id": "301",
          "svc_scat_id": "2",
          "svc_description": "Outdoor Plumbing",
          "svc_code": "MTN-PL009",
          "svc_sort": "0",
          "scat_id": "2",
          "scat_category": "Plumbing, Water & Sewage",
          "scat_icon": "i82fb1587325327961.png",
          "scat_is_general": "0",
          "scat_service_area_id": "1",
          "scat_sort": "2"
        },
        {
          "svc_id": "663",
          "svc_scat_id": "2",
          "svc_description": "Septic Evacuation / Sewage Treatment",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "2",
          "scat_category": "Plumbing, Water & Sewage",
          "scat_icon": "i82fb1587325327961.png",
          "scat_is_general": "0",
          "scat_service_area_id": "1",
          "scat_sort": "2"
        },
        {
          "svc_id": "697",
          "svc_scat_id": "2",
          "svc_description": "Service Water Dispenser",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "2",
          "scat_category": "Plumbing, Water & Sewage",
          "scat_icon": "i82fb1587325327961.png",
          "scat_is_general": "0",
          "scat_service_area_id": "1",
          "scat_sort": "2"
        },
        {
          "svc_id": "658",
          "svc_scat_id": "2",
          "svc_description": "Shower / Bathtub",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "2",
          "scat_category": "Plumbing, Water & Sewage",
          "scat_icon": "i82fb1587325327961.png",
          "scat_is_general": "0",
          "scat_service_area_id": "1",
          "scat_sort": "2"
        },
        {
          "svc_id": "657",
          "svc_scat_id": "2",
          "svc_description": "Sink / Faucet",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "2",
          "scat_category": "Plumbing, Water & Sewage",
          "scat_icon": "i82fb1587325327961.png",
          "scat_is_general": "0",
          "scat_service_area_id": "1",
          "scat_sort": "2"
        },
        {
          "svc_id": "478",
          "svc_scat_id": "2",
          "svc_description": "Toilet WC not Flushing",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "2",
          "scat_category": "Plumbing, Water & Sewage",
          "scat_icon": "i82fb1587325327961.png",
          "scat_is_general": "0",
          "scat_service_area_id": "1",
          "scat_sort": "2"
        },
        {
          "svc_id": "473",
          "svc_scat_id": "2",
          "svc_description": "Unpleasant  Odour",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "2",
          "scat_category": "Plumbing, Water & Sewage",
          "scat_icon": "i82fb1587325327961.png",
          "scat_is_general": "0",
          "scat_service_area_id": "1",
          "scat_sort": "2"
        },
        {
          "svc_id": "660",
          "svc_scat_id": "2",
          "svc_description": "Washing Machine",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "2",
          "scat_category": "Plumbing, Water & Sewage",
          "scat_icon": "i82fb1587325327961.png",
          "scat_is_general": "0",
          "scat_service_area_id": "1",
          "scat_sort": "2"
        },
        {
          "svc_id": "661",
          "svc_scat_id": "2",
          "svc_description": "Water Heater",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "2",
          "scat_category": "Plumbing, Water & Sewage",
          "scat_icon": "i82fb1587325327961.png",
          "scat_is_general": "0",
          "scat_service_area_id": "1",
          "scat_sort": "2"
        },
        {
          "svc_id": "662",
          "svc_scat_id": "2",
          "svc_description": "Water Treatment Plant",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "2",
          "scat_category": "Plumbing, Water & Sewage",
          "scat_icon": "i82fb1587325327961.png",
          "scat_is_general": "0",
          "scat_service_area_id": "1",
          "scat_sort": "2"
        },
        {
          "svc_id": "437",
          "svc_scat_id": "2",
          "svc_description": "Others",
          "svc_code": null,
          "svc_sort": "1",
          "scat_id": "2",
          "scat_category": "Plumbing, Water & Sewage",
          "scat_icon": "i82fb1587325327961.png",
          "scat_is_general": "0",
          "scat_service_area_id": "1",
          "scat_sort": "2"
        },
        {
          "svc_id": "700",
          "svc_scat_id": "10",
          "svc_description": "Building Renovations & Refurbishment",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "10",
          "scat_category": "Civil Works & Painting",
          "scat_icon": "bvadyd1587325381041.png",
          "scat_is_general": "0",
          "scat_service_area_id": "1",
          "scat_sort": "3"
        },
        {
          "svc_id": "113",
          "svc_scat_id": "10",
          "svc_description": "Ceiling Maintenance",
          "svc_code": "MTN-CV020",
          "svc_sort": "0",
          "scat_id": "10",
          "scat_category": "Civil Works & Painting",
          "scat_icon": "bvadyd1587325381041.png",
          "scat_is_general": "0",
          "scat_service_area_id": "1",
          "scat_sort": "3"
        },
        {
          "svc_id": "111",
          "svc_scat_id": "10",
          "svc_description": "Cracked Wall Repairs",
          "svc_code": "MTN-CV018",
          "svc_sort": "0",
          "scat_id": "10",
          "scat_category": "Civil Works & Painting",
          "scat_icon": "bvadyd1587325381041.png",
          "scat_is_general": "0",
          "scat_service_area_id": "1",
          "scat_sort": "3"
        },
        {
          "svc_id": "714",
          "svc_scat_id": "10",
          "svc_description": "Internal Roads and Drains Maintenance",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "10",
          "scat_category": "Civil Works & Painting",
          "scat_icon": "bvadyd1587325381041.png",
          "scat_is_general": "0",
          "scat_service_area_id": "1",
          "scat_sort": "3"
        },
        {
          "svc_id": "715",
          "svc_scat_id": "10",
          "svc_description": "Laying and Repair of Interlocking Stones",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "10",
          "scat_category": "Civil Works & Painting",
          "scat_icon": "bvadyd1587325381041.png",
          "scat_is_general": "0",
          "scat_service_area_id": "1",
          "scat_sort": "3"
        },
        {
          "svc_id": "685",
          "svc_scat_id": "10",
          "svc_description": "Painting",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "10",
          "scat_category": "Civil Works & Painting",
          "scat_icon": "bvadyd1587325381041.png",
          "scat_is_general": "0",
          "scat_service_area_id": "1",
          "scat_sort": "3"
        },
        {
          "svc_id": "624",
          "svc_scat_id": "10",
          "svc_description": "Plastering",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "10",
          "scat_category": "Civil Works & Painting",
          "scat_icon": "bvadyd1587325381041.png",
          "scat_is_general": "0",
          "scat_service_area_id": "1",
          "scat_sort": "3"
        },
        {
          "svc_id": "386",
          "svc_scat_id": "10",
          "svc_description": "Roofing & Maintenance",
          "svc_code": "MTN-CV036",
          "svc_sort": "0",
          "scat_id": "10",
          "scat_category": "Civil Works & Painting",
          "scat_icon": "bvadyd1587325381041.png",
          "scat_is_general": "0",
          "scat_service_area_id": "1",
          "scat_sort": "3"
        },
        {
          "svc_id": "701",
          "svc_scat_id": "10",
          "svc_description": "Space Planning & Remodeling",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "10",
          "scat_category": "Civil Works & Painting",
          "scat_icon": "bvadyd1587325381041.png",
          "scat_is_general": "0",
          "scat_service_area_id": "1",
          "scat_sort": "3"
        },
        {
          "svc_id": "684",
          "svc_scat_id": "10",
          "svc_description": "Tiling",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "10",
          "scat_category": "Civil Works & Painting",
          "scat_icon": "bvadyd1587325381041.png",
          "scat_is_general": "0",
          "scat_service_area_id": "1",
          "scat_sort": "3"
        },
        {
          "svc_id": "472",
          "svc_scat_id": "10",
          "svc_description": "Water Proofing",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "10",
          "scat_category": "Civil Works & Painting",
          "scat_icon": "bvadyd1587325381041.png",
          "scat_is_general": "0",
          "scat_service_area_id": "1",
          "scat_sort": "3"
        },
        {
          "svc_id": "682",
          "svc_scat_id": "10",
          "svc_description": "Welding and Metal Works",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "10",
          "scat_category": "Civil Works & Painting",
          "scat_icon": "bvadyd1587325381041.png",
          "scat_is_general": "0",
          "scat_service_area_id": "1",
          "scat_sort": "3"
        },
        {
          "svc_id": "116",
          "svc_scat_id": "10",
          "svc_description": "Others",
          "svc_code": "MTN-CV023",
          "svc_sort": "1",
          "scat_id": "10",
          "scat_category": "Civil Works & Painting",
          "scat_icon": "bvadyd1587325381041.png",
          "scat_is_general": "0",
          "scat_service_area_id": "1",
          "scat_sort": "3"
        },
        {
          "svc_id": "732",
          "svc_scat_id": "64",
          "svc_description": "Auto and residential",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "64",
          "scat_category": "Locksmith",
          "scat_icon": "snrnig1612180838707.png",
          "scat_is_general": "0",
          "scat_service_area_id": "1",
          "scat_sort": "4"
        },
        {
          "svc_id": "733",
          "svc_scat_id": "64",
          "svc_description": "Fixing / repair of lock",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "64",
          "scat_category": "Locksmith",
          "scat_icon": "snrnig1612180838707.png",
          "scat_is_general": "0",
          "scat_service_area_id": "1",
          "scat_sort": "4"
        },
        {
          "svc_id": "734",
          "svc_scat_id": "64",
          "svc_description": "Repair and servicing of safe and vault",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "64",
          "scat_category": "Locksmith",
          "scat_icon": "snrnig1612180838707.png",
          "scat_is_general": "0",
          "scat_service_area_id": "1",
          "scat_sort": "4"
        },
        {
          "svc_id": "736",
          "svc_scat_id": "64",
          "svc_description": "Transponder key programming",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "64",
          "scat_category": "Locksmith",
          "scat_icon": "snrnig1612180838707.png",
          "scat_is_general": "0",
          "scat_service_area_id": "1",
          "scat_sort": "4"
        },
        {
          "svc_id": "735",
          "svc_scat_id": "64",
          "svc_description": "Vehicle ignition lock repair",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "64",
          "scat_category": "Locksmith",
          "scat_icon": "snrnig1612180838707.png",
          "scat_is_general": "0",
          "scat_service_area_id": "1",
          "scat_sort": "4"
        },
        {
          "svc_id": "542",
          "svc_scat_id": "4",
          "svc_description": "HVAC (Chilled, Air Handling Units, etc)",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "4",
          "scat_category": "Air Conditioning / HVAC Systems",
          "scat_icon": "my3b31587325429674.png",
          "scat_is_general": "0",
          "scat_service_area_id": "1",
          "scat_sort": "5"
        },
        {
          "svc_id": "465",
          "svc_scat_id": "4",
          "svc_description": "Packaged Unit AC",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "4",
          "scat_category": "Air Conditioning / HVAC Systems",
          "scat_icon": "my3b31587325429674.png",
          "scat_is_general": "0",
          "scat_service_area_id": "1",
          "scat_sort": "5"
        },
        {
          "svc_id": "462",
          "svc_scat_id": "4",
          "svc_description": "Portable AC",
          "svc_code": "ACU-001",
          "svc_sort": "0",
          "scat_id": "4",
          "scat_category": "Air Conditioning / HVAC Systems",
          "scat_icon": "my3b31587325429674.png",
          "scat_is_general": "0",
          "scat_service_area_id": "1",
          "scat_sort": "5"
        },
        {
          "svc_id": "463",
          "svc_scat_id": "4",
          "svc_description": "Split Unit AC",
          "svc_code": "MTN-AC008",
          "svc_sort": "0",
          "scat_id": "4",
          "scat_category": "Air Conditioning / HVAC Systems",
          "scat_icon": "my3b31587325429674.png",
          "scat_is_general": "0",
          "scat_service_area_id": "1",
          "scat_sort": "5"
        },
        {
          "svc_id": "42",
          "svc_scat_id": "4",
          "svc_description": "Window Units AC",
          "svc_code": "MTN-AC009",
          "svc_sort": "0",
          "scat_id": "4",
          "scat_category": "Air Conditioning / HVAC Systems",
          "scat_icon": "my3b31587325429674.png",
          "scat_is_general": "0",
          "scat_service_area_id": "1",
          "scat_sort": "5"
        },
        {
          "svc_id": "40",
          "svc_scat_id": "4",
          "svc_description": "Others",
          "svc_code": "MTN-AC007",
          "svc_sort": "1",
          "scat_id": "4",
          "scat_category": "Air Conditioning / HVAC Systems",
          "scat_icon": "my3b31587325429674.png",
          "scat_is_general": "0",
          "scat_service_area_id": "1",
          "scat_sort": "5"
        },
        {
          "svc_id": "613",
          "svc_scat_id": "46",
          "svc_description": "Dosing System",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "46",
          "scat_category": "Swimming Pool Maintenance",
          "scat_icon": "6lq0w1575037821799.png",
          "scat_is_general": "0",
          "scat_service_area_id": "1",
          "scat_sort": "7"
        },
        {
          "svc_id": "614",
          "svc_scat_id": "46",
          "svc_description": "Pumps",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "46",
          "scat_category": "Swimming Pool Maintenance",
          "scat_icon": "6lq0w1575037821799.png",
          "scat_is_general": "0",
          "scat_service_area_id": "1",
          "scat_sort": "7"
        },
        {
          "svc_id": "616",
          "svc_scat_id": "46",
          "svc_description": "Swimming Pool Maintenance",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "46",
          "scat_category": "Swimming Pool Maintenance",
          "scat_icon": "6lq0w1575037821799.png",
          "scat_is_general": "0",
          "scat_service_area_id": "1",
          "scat_sort": "7"
        },
        {
          "svc_id": "630",
          "svc_scat_id": "46",
          "svc_description": "Others",
          "svc_code": null,
          "svc_sort": "1",
          "scat_id": "46",
          "scat_category": "Swimming Pool Maintenance",
          "scat_icon": "6lq0w1575037821799.png",
          "scat_is_general": "0",
          "scat_service_area_id": "1",
          "scat_sort": "7"
        },
        {
          "svc_id": "403",
          "svc_scat_id": "8",
          "svc_description": "Ceiling & POP",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "8",
          "scat_category": "Carpentry & Furniture Repairs",
          "scat_icon": "carpentry.png",
          "scat_is_general": "0",
          "scat_service_area_id": "1",
          "scat_sort": "9"
        },
        {
          "svc_id": "500",
          "svc_scat_id": "8",
          "svc_description": "Doors & Windows",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "8",
          "scat_category": "Carpentry & Furniture Repairs",
          "scat_icon": "carpentry.png",
          "scat_is_general": "0",
          "scat_service_area_id": "1",
          "scat_sort": "9"
        },
        {
          "svc_id": "402",
          "svc_scat_id": "8",
          "svc_description": "Furniture Repairs",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "8",
          "scat_category": "Carpentry & Furniture Repairs",
          "scat_icon": "carpentry.png",
          "scat_is_general": "0",
          "scat_service_area_id": "1",
          "scat_sort": "9"
        },
        {
          "svc_id": "669",
          "svc_scat_id": "8",
          "svc_description": "Glass Installation / Repair / Replacement",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "8",
          "scat_category": "Carpentry & Furniture Repairs",
          "scat_icon": "carpentry.png",
          "scat_is_general": "0",
          "scat_service_area_id": "1",
          "scat_sort": "9"
        },
        {
          "svc_id": "668",
          "svc_scat_id": "8",
          "svc_description": "Locks Repair / Replacement",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "8",
          "scat_category": "Carpentry & Furniture Repairs",
          "scat_icon": "carpentry.png",
          "scat_is_general": "0",
          "scat_service_area_id": "1",
          "scat_sort": "9"
        },
        {
          "svc_id": "79",
          "svc_scat_id": "8",
          "svc_description": "Shelves / Cabinets",
          "svc_code": "CPT-003",
          "svc_sort": "0",
          "scat_id": "8",
          "scat_category": "Carpentry & Furniture Repairs",
          "scat_icon": "carpentry.png",
          "scat_is_general": "0",
          "scat_service_area_id": "1",
          "scat_sort": "9"
        },
        {
          "svc_id": "77",
          "svc_scat_id": "8",
          "svc_description": "Stairs",
          "svc_code": "CPT-001",
          "svc_sort": "0",
          "scat_id": "8",
          "scat_category": "Carpentry & Furniture Repairs",
          "scat_icon": "carpentry.png",
          "scat_is_general": "0",
          "scat_service_area_id": "1",
          "scat_sort": "9"
        },
        {
          "svc_id": "81",
          "svc_scat_id": "8",
          "svc_description": "Others",
          "svc_code": "CPT-005",
          "svc_sort": "1",
          "scat_id": "8",
          "scat_category": "Carpentry & Furniture Repairs",
          "scat_icon": "carpentry.png",
          "scat_is_general": "0",
          "scat_service_area_id": "1",
          "scat_sort": "9"
        },
        {
          "svc_id": "572",
          "svc_scat_id": "41",
          "svc_description": "Carpeting and Rug Laying",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "41",
          "scat_category": "Interior Decorations",
          "scat_icon": "bg8opa1588009591000.png",
          "scat_is_general": "0",
          "scat_service_area_id": "1",
          "scat_sort": "11"
        },
        {
          "svc_id": "551",
          "svc_scat_id": "41",
          "svc_description": "Curtains and Window Blinds",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "41",
          "scat_category": "Interior Decorations",
          "scat_icon": "bg8opa1588009591000.png",
          "scat_is_general": "0",
          "scat_service_area_id": "1",
          "scat_sort": "11"
        },
        {
          "svc_id": "573",
          "svc_scat_id": "41",
          "svc_description": "Event Hall Decorations",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "41",
          "scat_category": "Interior Decorations",
          "scat_icon": "bg8opa1588009591000.png",
          "scat_is_general": "0",
          "scat_service_area_id": "1",
          "scat_sort": "11"
        },
        {
          "svc_id": "574",
          "svc_scat_id": "41",
          "svc_description": "Home Decoration",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "41",
          "scat_category": "Interior Decorations",
          "scat_icon": "bg8opa1588009591000.png",
          "scat_is_general": "0",
          "scat_service_area_id": "1",
          "scat_sort": "11"
        },
        {
          "svc_id": "575",
          "svc_scat_id": "41",
          "svc_description": "Wall Paper",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "41",
          "scat_category": "Interior Decorations",
          "scat_icon": "bg8opa1588009591000.png",
          "scat_is_general": "0",
          "scat_service_area_id": "1",
          "scat_sort": "11"
        },
        {
          "svc_id": "418",
          "svc_scat_id": "11",
          "svc_description": "Deep Cleaning (Internal & External  Env.)",
          "svc_code": "CLN-008",
          "svc_sort": "0",
          "scat_id": "11",
          "scat_category": "Cleaning & Fumigation Services",
          "scat_icon": "cleaning.png",
          "scat_is_general": "0",
          "scat_service_area_id": "1",
          "scat_sort": "13"
        },
        {
          "svc_id": "89",
          "svc_scat_id": "11",
          "svc_description": "Domestic Cleaning Services",
          "svc_code": "MTN-CT006",
          "svc_sort": "0",
          "scat_id": "11",
          "scat_category": "Cleaning & Fumigation Services",
          "scat_icon": "cleaning.png",
          "scat_is_general": "0",
          "scat_service_area_id": "1",
          "scat_sort": "13"
        },
        {
          "svc_id": "642",
          "svc_scat_id": "11",
          "svc_description": "Fumigation",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "11",
          "scat_category": "Cleaning & Fumigation Services",
          "scat_icon": "cleaning.png",
          "scat_is_general": "0",
          "scat_service_area_id": "1",
          "scat_sort": "13"
        },
        {
          "svc_id": "741",
          "svc_scat_id": "11",
          "svc_description": "Housekeeping and domestic support",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "11",
          "scat_category": "Cleaning & Fumigation Services",
          "scat_icon": "cleaning.png",
          "scat_is_general": "0",
          "scat_service_area_id": "1",
          "scat_sort": "13"
        },
        {
          "svc_id": "716",
          "svc_scat_id": "11",
          "svc_description": "Interlocking / Paving Stones Cleaning",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "11",
          "scat_category": "Cleaning & Fumigation Services",
          "scat_icon": "cleaning.png",
          "scat_is_general": "0",
          "scat_service_area_id": "1",
          "scat_sort": "13"
        },
        {
          "svc_id": "556",
          "svc_scat_id": "11",
          "svc_description": "Pest Control",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "11",
          "scat_category": "Cleaning & Fumigation Services",
          "scat_icon": "cleaning.png",
          "scat_is_general": "0",
          "scat_service_area_id": "1",
          "scat_sort": "13"
        },
        {
          "svc_id": "414",
          "svc_scat_id": "11",
          "svc_description": "Refuse Collection & Removal",
          "svc_code": "CLN-00",
          "svc_sort": "0",
          "scat_id": "11",
          "scat_category": "Cleaning & Fumigation Services",
          "scat_icon": "cleaning.png",
          "scat_is_general": "0",
          "scat_service_area_id": "1",
          "scat_sort": "13"
        },
        {
          "svc_id": "555",
          "svc_scat_id": "11",
          "svc_description": "Roads and Drains Cleaning",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "11",
          "scat_category": "Cleaning & Fumigation Services",
          "scat_icon": "cleaning.png",
          "scat_is_general": "0",
          "scat_service_area_id": "1",
          "scat_sort": "13"
        },
        {
          "svc_id": "557",
          "svc_scat_id": "11",
          "svc_description": "Rodents Control",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "11",
          "scat_category": "Cleaning & Fumigation Services",
          "scat_icon": "cleaning.png",
          "scat_is_general": "0",
          "scat_service_area_id": "1",
          "scat_sort": "13"
        },
        {
          "svc_id": "415",
          "svc_scat_id": "11",
          "svc_description": "Street Sweeping",
          "svc_code": "CLN-005",
          "svc_sort": "0",
          "scat_id": "11",
          "scat_category": "Cleaning & Fumigation Services",
          "scat_icon": "cleaning.png",
          "scat_is_general": "0",
          "scat_service_area_id": "1",
          "scat_sort": "13"
        },
        {
          "svc_id": "438",
          "svc_scat_id": "11",
          "svc_description": "Others",
          "svc_code": null,
          "svc_sort": "1",
          "scat_id": "11",
          "scat_category": "Cleaning & Fumigation Services",
          "scat_icon": "cleaning.png",
          "scat_is_general": "0",
          "scat_service_area_id": "1",
          "scat_sort": "13"
        },
        {
          "svc_id": "486",
          "svc_scat_id": "33",
          "svc_description": "Fertilization  and Weed Control",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "33",
          "scat_category": "Gardening & Landscaping",
          "scat_icon": "flowers.png",
          "scat_is_general": "0",
          "scat_service_area_id": "1",
          "scat_sort": "14"
        },
        {
          "svc_id": "645",
          "svc_scat_id": "33",
          "svc_description": "Flower Pots",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "33",
          "scat_category": "Gardening & Landscaping",
          "scat_icon": "flowers.png",
          "scat_is_general": "0",
          "scat_service_area_id": "1",
          "scat_sort": "14"
        },
        {
          "svc_id": "479",
          "svc_scat_id": "33",
          "svc_description": "Gardening Services",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "33",
          "scat_category": "Gardening & Landscaping",
          "scat_icon": "flowers.png",
          "scat_is_general": "0",
          "scat_service_area_id": "1",
          "scat_sort": "14"
        },
        {
          "svc_id": "480",
          "svc_scat_id": "33",
          "svc_description": "Gardening Tools and Equipment",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "33",
          "scat_category": "Gardening & Landscaping",
          "scat_icon": "flowers.png",
          "scat_is_general": "0",
          "scat_service_area_id": "1",
          "scat_sort": "14"
        },
        {
          "svc_id": "483",
          "svc_scat_id": "33",
          "svc_description": "Horticultural/Landscaping",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "33",
          "scat_category": "Gardening & Landscaping",
          "scat_icon": "flowers.png",
          "scat_is_general": "0",
          "scat_service_area_id": "1",
          "scat_sort": "14"
        },
        {
          "svc_id": "487",
          "svc_scat_id": "33",
          "svc_description": "Landfill Revegetation",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "33",
          "scat_category": "Gardening & Landscaping",
          "scat_icon": "flowers.png",
          "scat_is_general": "0",
          "scat_service_area_id": "1",
          "scat_sort": "14"
        },
        {
          "svc_id": "482",
          "svc_scat_id": "33",
          "svc_description": "Lawn Mowing",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "33",
          "scat_category": "Gardening & Landscaping",
          "scat_icon": "flowers.png",
          "scat_is_general": "0",
          "scat_service_area_id": "1",
          "scat_sort": "14"
        },
        {
          "svc_id": "484",
          "svc_scat_id": "33",
          "svc_description": "Parks and Open Space Services",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "33",
          "scat_category": "Gardening & Landscaping",
          "scat_icon": "flowers.png",
          "scat_is_general": "0",
          "scat_service_area_id": "1",
          "scat_sort": "14"
        },
        {
          "svc_id": "644",
          "svc_scat_id": "33",
          "svc_description": "Tree Trimming",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "33",
          "scat_category": "Gardening & Landscaping",
          "scat_icon": "flowers.png",
          "scat_is_general": "0",
          "scat_service_area_id": "1",
          "scat_sort": "14"
        },
        {
          "svc_id": "631",
          "svc_scat_id": "33",
          "svc_description": "Others",
          "svc_code": null,
          "svc_sort": "1",
          "scat_id": "33",
          "scat_category": "Gardening & Landscaping",
          "scat_icon": "flowers.png",
          "scat_is_general": "0",
          "scat_service_area_id": "1",
          "scat_sort": "14"
        },
        {
          "svc_id": "254",
          "svc_scat_id": "30",
          "svc_description": "Dish washer",
          "svc_code": "MTN-WT013",
          "svc_sort": "0",
          "scat_id": "30",
          "scat_category": "Home Electronics",
          "scat_icon": "domestic.png",
          "scat_is_general": "0",
          "scat_service_area_id": "2",
          "scat_sort": "15"
        },
        {
          "svc_id": "681",
          "svc_scat_id": "30",
          "svc_description": "DSTV Services",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "30",
          "scat_category": "Home Electronics",
          "scat_icon": "domestic.png",
          "scat_is_general": "0",
          "scat_service_area_id": "2",
          "scat_sort": "15"
        },
        {
          "svc_id": "702",
          "svc_scat_id": "30",
          "svc_description": "Electric Cooker",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "30",
          "scat_category": "Home Electronics",
          "scat_icon": "domestic.png",
          "scat_is_general": "0",
          "scat_service_area_id": "2",
          "scat_sort": "15"
        },
        {
          "svc_id": "427",
          "svc_scat_id": "30",
          "svc_description": "Fan",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "30",
          "scat_category": "Home Electronics",
          "scat_icon": "domestic.png",
          "scat_is_general": "0",
          "scat_service_area_id": "2",
          "scat_sort": "15"
        },
        {
          "svc_id": "703",
          "svc_scat_id": "30",
          "svc_description": "Gas Cooker",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "30",
          "scat_category": "Home Electronics",
          "scat_icon": "domestic.png",
          "scat_is_general": "0",
          "scat_service_area_id": "2",
          "scat_sort": "15"
        },
        {
          "svc_id": "425",
          "svc_scat_id": "30",
          "svc_description": "Humidifier",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "30",
          "scat_category": "Home Electronics",
          "scat_icon": "domestic.png",
          "scat_is_general": "0",
          "scat_service_area_id": "2",
          "scat_sort": "15"
        },
        {
          "svc_id": "423",
          "svc_scat_id": "30",
          "svc_description": "Microwave",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "30",
          "scat_category": "Home Electronics",
          "scat_icon": "domestic.png",
          "scat_is_general": "0",
          "scat_service_area_id": "2",
          "scat_sort": "15"
        },
        {
          "svc_id": "495",
          "svc_scat_id": "30",
          "svc_description": "Refrigerators & Freezers",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "30",
          "scat_category": "Home Electronics",
          "scat_icon": "domestic.png",
          "scat_is_general": "0",
          "scat_service_area_id": "2",
          "scat_sort": "15"
        },
        {
          "svc_id": "424",
          "svc_scat_id": "30",
          "svc_description": "Television",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "30",
          "scat_category": "Home Electronics",
          "scat_icon": "domestic.png",
          "scat_is_general": "0",
          "scat_service_area_id": "2",
          "scat_sort": "15"
        },
        {
          "svc_id": "422",
          "svc_scat_id": "30",
          "svc_description": "Washing Machine",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "30",
          "scat_category": "Home Electronics",
          "scat_icon": "domestic.png",
          "scat_is_general": "0",
          "scat_service_area_id": "2",
          "scat_sort": "15"
        },
        {
          "svc_id": "426",
          "svc_scat_id": "30",
          "svc_description": "Water  Heater",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "30",
          "scat_category": "Home Electronics",
          "scat_icon": "domestic.png",
          "scat_is_general": "0",
          "scat_service_area_id": "2",
          "scat_sort": "15"
        },
        {
          "svc_id": "428",
          "svc_scat_id": "30",
          "svc_description": "Others",
          "svc_code": null,
          "svc_sort": "1",
          "scat_id": "30",
          "scat_category": "Home Electronics",
          "scat_icon": "domestic.png",
          "scat_is_general": "0",
          "scat_service_area_id": "2",
          "scat_sort": "15"
        },
        {
          "svc_id": "431",
          "svc_scat_id": "32",
          "svc_description": "Audio -Visual Equipment",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "32",
          "scat_category": "Office Equipment",
          "scat_icon": "office-equipment.png",
          "scat_is_general": "0",
          "scat_service_area_id": "2",
          "scat_sort": "16"
        },
        {
          "svc_id": "404",
          "svc_scat_id": "32",
          "svc_description": "Computers and Laptop",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "32",
          "scat_category": "Office Equipment",
          "scat_icon": "office-equipment.png",
          "scat_is_general": "0",
          "scat_service_area_id": "2",
          "scat_sort": "16"
        },
        {
          "svc_id": "580",
          "svc_scat_id": "32",
          "svc_description": "Doors Labels & Directional Signs",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "32",
          "scat_category": "Office Equipment",
          "scat_icon": "office-equipment.png",
          "scat_is_general": "0",
          "scat_service_area_id": "2",
          "scat_sort": "16"
        },
        {
          "svc_id": "496",
          "svc_scat_id": "32",
          "svc_description": "Intercom Services",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "32",
          "scat_category": "Office Equipment",
          "scat_icon": "office-equipment.png",
          "scat_is_general": "0",
          "scat_service_area_id": "2",
          "scat_sort": "16"
        },
        {
          "svc_id": "434",
          "svc_scat_id": "32",
          "svc_description": "Internet Services",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "32",
          "scat_category": "Office Equipment",
          "scat_icon": "office-equipment.png",
          "scat_is_general": "0",
          "scat_service_area_id": "2",
          "scat_sort": "16"
        },
        {
          "svc_id": "593",
          "svc_scat_id": "32",
          "svc_description": "Office Accessories and Toiletries Supply",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "32",
          "scat_category": "Office Equipment",
          "scat_icon": "office-equipment.png",
          "scat_is_general": "0",
          "scat_service_area_id": "2",
          "scat_sort": "16"
        },
        {
          "svc_id": "581",
          "svc_scat_id": "32",
          "svc_description": "Office Furnishing",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "32",
          "scat_category": "Office Equipment",
          "scat_icon": "office-equipment.png",
          "scat_is_general": "0",
          "scat_service_area_id": "2",
          "scat_sort": "16"
        },
        {
          "svc_id": "579",
          "svc_scat_id": "32",
          "svc_description": "Office Space Planning  & Remodelling",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "32",
          "scat_category": "Office Equipment",
          "scat_icon": "office-equipment.png",
          "scat_is_general": "0",
          "scat_service_area_id": "2",
          "scat_sort": "16"
        },
        {
          "svc_id": "405",
          "svc_scat_id": "32",
          "svc_description": "Photocopiers, Printets and Scannner",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "32",
          "scat_category": "Office Equipment",
          "scat_icon": "office-equipment.png",
          "scat_is_general": "0",
          "scat_service_area_id": "2",
          "scat_sort": "16"
        },
        {
          "svc_id": "432",
          "svc_scat_id": "32",
          "svc_description": "Projectors",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "32",
          "scat_category": "Office Equipment",
          "scat_icon": "office-equipment.png",
          "scat_is_general": "0",
          "scat_service_area_id": "2",
          "scat_sort": "16"
        },
        {
          "svc_id": "632",
          "svc_scat_id": "32",
          "svc_description": "Others",
          "svc_code": null,
          "svc_sort": "1",
          "scat_id": "32",
          "scat_category": "Office Equipment",
          "scat_icon": "office-equipment.png",
          "scat_is_general": "0",
          "scat_service_area_id": "2",
          "scat_sort": "16"
        },
        {
          "svc_id": "666",
          "svc_scat_id": "13",
          "svc_description": "Body Scanner",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "13",
          "scat_category": "Safety & Security Systems",
          "scat_icon": "fire-detection.png",
          "scat_is_general": "0",
          "scat_service_area_id": "1",
          "scat_sort": "18"
        },
        {
          "svc_id": "586",
          "svc_scat_id": "13",
          "svc_description": "CCTV",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "13",
          "scat_category": "Safety & Security Systems",
          "scat_icon": "fire-detection.png",
          "scat_is_general": "0",
          "scat_service_area_id": "1",
          "scat_sort": "18"
        },
        {
          "svc_id": "453",
          "svc_scat_id": "13",
          "svc_description": "Electric Fence",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "13",
          "scat_category": "Safety & Security Systems",
          "scat_icon": "fire-detection.png",
          "scat_is_general": "0",
          "scat_service_area_id": "1",
          "scat_sort": "18"
        },
        {
          "svc_id": "447",
          "svc_scat_id": "13",
          "svc_description": "Fire Alarm",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "13",
          "scat_category": "Safety & Security Systems",
          "scat_icon": "fire-detection.png",
          "scat_is_general": "0",
          "scat_service_area_id": "1",
          "scat_sort": "18"
        },
        {
          "svc_id": "396",
          "svc_scat_id": "13",
          "svc_description": "Intruder Detection / Access Control",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "13",
          "scat_category": "Safety & Security Systems",
          "scat_icon": "fire-detection.png",
          "scat_is_general": "0",
          "scat_service_area_id": "1",
          "scat_sort": "18"
        },
        {
          "svc_id": "667",
          "svc_scat_id": "13",
          "svc_description": "Motorised Gate",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "13",
          "scat_category": "Safety & Security Systems",
          "scat_icon": "fire-detection.png",
          "scat_is_general": "0",
          "scat_service_area_id": "1",
          "scat_sort": "18"
        },
        {
          "svc_id": "160",
          "svc_scat_id": "13",
          "svc_description": "Smoke  & Heat Detectors",
          "svc_code": "FRD-002",
          "svc_sort": "0",
          "scat_id": "13",
          "scat_category": "Safety & Security Systems",
          "scat_icon": "fire-detection.png",
          "scat_is_general": "0",
          "scat_service_area_id": "1",
          "scat_sort": "18"
        },
        {
          "svc_id": "452",
          "svc_scat_id": "13",
          "svc_description": "Sprinkler System",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "13",
          "scat_category": "Safety & Security Systems",
          "scat_icon": "fire-detection.png",
          "scat_is_general": "0",
          "scat_service_area_id": "1",
          "scat_sort": "18"
        },
        {
          "svc_id": "421",
          "svc_scat_id": "13",
          "svc_description": "Others",
          "svc_code": null,
          "svc_sort": "1",
          "scat_id": "13",
          "scat_category": "Safety & Security Systems",
          "scat_icon": "fire-detection.png",
          "scat_is_general": "0",
          "scat_service_area_id": "1",
          "scat_sort": "18"
        },
        {
          "svc_id": "690",
          "svc_scat_id": "55",
          "svc_description": "Doorbell",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "55",
          "scat_category": "ICT/Internet Services",
          "scat_icon": "ppzlor1587367221435.png",
          "scat_is_general": "0",
          "scat_service_area_id": "1",
          "scat_sort": "19"
        },
        {
          "svc_id": "692",
          "svc_scat_id": "55",
          "svc_description": "Intercom Telephone Connectivity",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "55",
          "scat_category": "ICT/Internet Services",
          "scat_icon": "ppzlor1587367221435.png",
          "scat_is_general": "0",
          "scat_service_area_id": "1",
          "scat_sort": "19"
        },
        {
          "svc_id": "686",
          "svc_scat_id": "55",
          "svc_description": "Internet  Connection",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "55",
          "scat_category": "ICT/Internet Services",
          "scat_icon": "ppzlor1587367221435.png",
          "scat_is_general": "0",
          "scat_service_area_id": "1",
          "scat_sort": "19"
        },
        {
          "svc_id": "693",
          "svc_scat_id": "55",
          "svc_description": "Laptop / Desktop Computers",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "55",
          "scat_category": "ICT/Internet Services",
          "scat_icon": "ppzlor1587367221435.png",
          "scat_is_general": "0",
          "scat_service_area_id": "1",
          "scat_sort": "19"
        },
        {
          "svc_id": "694",
          "svc_scat_id": "55",
          "svc_description": "Laptop / Desktop Monitor",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "55",
          "scat_category": "ICT/Internet Services",
          "scat_icon": "ppzlor1587367221435.png",
          "scat_is_general": "0",
          "scat_service_area_id": "1",
          "scat_sort": "19"
        },
        {
          "svc_id": "687",
          "svc_scat_id": "55",
          "svc_description": "Local Area Connection Problem (LAN)",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "55",
          "scat_category": "ICT/Internet Services",
          "scat_icon": "ppzlor1587367221435.png",
          "scat_is_general": "0",
          "scat_service_area_id": "1",
          "scat_sort": "19"
        },
        {
          "svc_id": "695",
          "svc_scat_id": "55",
          "svc_description": "Others (Specify)",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "55",
          "scat_category": "ICT/Internet Services",
          "scat_icon": "ppzlor1587367221435.png",
          "scat_is_general": "0",
          "scat_service_area_id": "1",
          "scat_sort": "19"
        },
        {
          "svc_id": "689",
          "svc_scat_id": "55",
          "svc_description": "Poor Telephone Network Reception",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "55",
          "scat_category": "ICT/Internet Services",
          "scat_icon": "ppzlor1587367221435.png",
          "scat_is_general": "0",
          "scat_service_area_id": "1",
          "scat_sort": "19"
        },
        {
          "svc_id": "691",
          "svc_scat_id": "55",
          "svc_description": "Video Intercom Connectivity",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "55",
          "scat_category": "ICT/Internet Services",
          "scat_icon": "ppzlor1587367221435.png",
          "scat_is_general": "0",
          "scat_service_area_id": "1",
          "scat_sort": "19"
        },
        {
          "svc_id": "688",
          "svc_scat_id": "55",
          "svc_description": "Wide Area Network Problem (WAN)",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "55",
          "scat_category": "ICT/Internet Services",
          "scat_icon": "ppzlor1587367221435.png",
          "scat_is_general": "0",
          "scat_service_area_id": "1",
          "scat_sort": "19"
        },
        {
          "svc_id": "515",
          "svc_scat_id": "34",
          "svc_description": "Cake Baking & Supply",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "34",
          "scat_category": "Catering & Event Management Services",
          "scat_icon": "chandelier.png",
          "scat_is_general": "0",
          "scat_service_area_id": "3",
          "scat_sort": "20"
        },
        {
          "svc_id": "514",
          "svc_scat_id": "34",
          "svc_description": "Catering",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "34",
          "scat_category": "Catering & Event Management Services",
          "scat_icon": "chandelier.png",
          "scat_is_general": "0",
          "scat_service_area_id": "3",
          "scat_sort": "20"
        },
        {
          "svc_id": "505",
          "svc_scat_id": "34",
          "svc_description": "Corporate Event Organisers",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "34",
          "scat_category": "Catering & Event Management Services",
          "scat_icon": "chandelier.png",
          "scat_is_general": "0",
          "scat_service_area_id": "3",
          "scat_sort": "20"
        },
        {
          "svc_id": "647",
          "svc_scat_id": "34",
          "svc_description": "Deejay / Comedians",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "34",
          "scat_category": "Catering & Event Management Services",
          "scat_icon": "chandelier.png",
          "scat_is_general": "0",
          "scat_service_area_id": "3",
          "scat_sort": "20"
        },
        {
          "svc_id": "511",
          "svc_scat_id": "34",
          "svc_description": "Hall and Space Rentals",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "34",
          "scat_category": "Catering & Event Management Services",
          "scat_icon": "chandelier.png",
          "scat_is_general": "0",
          "scat_service_area_id": "3",
          "scat_sort": "20"
        },
        {
          "svc_id": "509",
          "svc_scat_id": "34",
          "svc_description": "Master Of Ceremony",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "34",
          "scat_category": "Catering & Event Management Services",
          "scat_icon": "chandelier.png",
          "scat_is_general": "0",
          "scat_service_area_id": "3",
          "scat_sort": "20"
        },
        {
          "svc_id": "517",
          "svc_scat_id": "34",
          "svc_description": "Photography & Video Coverage",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "34",
          "scat_category": "Catering & Event Management Services",
          "scat_icon": "chandelier.png",
          "scat_is_general": "0",
          "scat_service_area_id": "3",
          "scat_sort": "20"
        },
        {
          "svc_id": "560",
          "svc_scat_id": "34",
          "svc_description": "Social Event Organiser",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "34",
          "scat_category": "Catering & Event Management Services",
          "scat_icon": "chandelier.png",
          "scat_is_general": "0",
          "scat_service_area_id": "3",
          "scat_sort": "20"
        },
        {
          "svc_id": "646",
          "svc_scat_id": "34",
          "svc_description": "Tea Coffers",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "34",
          "scat_category": "Catering & Event Management Services",
          "scat_icon": "chandelier.png",
          "scat_is_general": "0",
          "scat_service_area_id": "3",
          "scat_sort": "20"
        },
        {
          "svc_id": "648",
          "svc_scat_id": "34",
          "svc_description": "Undertakers",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "34",
          "scat_category": "Catering & Event Management Services",
          "scat_icon": "chandelier.png",
          "scat_is_general": "0",
          "scat_service_area_id": "3",
          "scat_sort": "20"
        },
        {
          "svc_id": "504",
          "svc_scat_id": "34",
          "svc_description": "Others",
          "svc_code": null,
          "svc_sort": "1",
          "scat_id": "34",
          "scat_category": "Catering & Event Management Services",
          "scat_icon": "chandelier.png",
          "scat_is_general": "0",
          "scat_service_area_id": "3",
          "scat_sort": "20"
        },
        {
          "svc_id": "638",
          "svc_scat_id": "50",
          "svc_description": "Biceps Curl Bench",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "50",
          "scat_category": "Kitchen Appliances",
          "scat_icon": "ygljz91587366015122.png",
          "scat_is_general": "0",
          "scat_service_area_id": "2",
          "scat_sort": "21"
        },
        {
          "svc_id": "637",
          "svc_scat_id": "50",
          "svc_description": "Cable Row Machine",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "50",
          "scat_category": "Kitchen Appliances",
          "scat_icon": "ygljz91587366015122.png",
          "scat_is_general": "0",
          "scat_service_area_id": "2",
          "scat_sort": "21"
        },
        {
          "svc_id": "635",
          "svc_scat_id": "50",
          "svc_description": "Chest Fly Machine",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "50",
          "scat_category": "Kitchen Appliances",
          "scat_icon": "ygljz91587366015122.png",
          "scat_is_general": "0",
          "scat_service_area_id": "2",
          "scat_sort": "21"
        },
        {
          "svc_id": "633",
          "svc_scat_id": "50",
          "svc_description": "Chest Press Machine",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "50",
          "scat_category": "Kitchen Appliances",
          "scat_icon": "ygljz91587366015122.png",
          "scat_is_general": "0",
          "scat_service_area_id": "2",
          "scat_sort": "21"
        },
        {
          "svc_id": "640",
          "svc_scat_id": "50",
          "svc_description": "Gymnasium Equipment Supplies",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "50",
          "scat_category": "Kitchen Appliances",
          "scat_icon": "ygljz91587366015122.png",
          "scat_is_general": "0",
          "scat_service_area_id": "2",
          "scat_sort": "21"
        },
        {
          "svc_id": "636",
          "svc_scat_id": "50",
          "svc_description": "Shoulder Press Machine",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "50",
          "scat_category": "Kitchen Appliances",
          "scat_icon": "ygljz91587366015122.png",
          "scat_is_general": "0",
          "scat_service_area_id": "2",
          "scat_sort": "21"
        },
        {
          "svc_id": "634",
          "svc_scat_id": "50",
          "svc_description": "Treadmill",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "50",
          "scat_category": "Kitchen Appliances",
          "scat_icon": "ygljz91587366015122.png",
          "scat_is_general": "0",
          "scat_service_area_id": "2",
          "scat_sort": "21"
        },
        {
          "svc_id": "639",
          "svc_scat_id": "50",
          "svc_description": "Triceps Extension Bar",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "50",
          "scat_category": "Kitchen Appliances",
          "scat_icon": "ygljz91587366015122.png",
          "scat_is_general": "0",
          "scat_service_area_id": "2",
          "scat_sort": "21"
        },
        {
          "svc_id": "641",
          "svc_scat_id": "50",
          "svc_description": "Others",
          "svc_code": null,
          "svc_sort": "1",
          "scat_id": "50",
          "scat_category": "Kitchen Appliances",
          "scat_icon": "ygljz91587366015122.png",
          "scat_is_general": "0",
          "scat_service_area_id": "2",
          "scat_sort": "21"
        },
        {
          "svc_id": "359",
          "svc_scat_id": "28",
          "svc_description": "Clinical Waste Management",
          "svc_code": "MTN-SW011",
          "svc_sort": "0",
          "scat_id": "28",
          "scat_category": "Waste Management & Environmental Services",
          "scat_icon": "sewage.png",
          "scat_is_general": "0",
          "scat_service_area_id": "1",
          "scat_sort": "22"
        },
        {
          "svc_id": "744",
          "svc_scat_id": "28",
          "svc_description": "Construction Waste Removal",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "28",
          "scat_category": "Waste Management & Environmental Services",
          "scat_icon": "sewage.png",
          "scat_is_general": "0",
          "scat_service_area_id": "1",
          "scat_sort": "22"
        },
        {
          "svc_id": "357",
          "svc_scat_id": "28",
          "svc_description": "Glass / Plastic / E-Waste Disposal",
          "svc_code": "MTN-SW009",
          "svc_sort": "0",
          "scat_id": "28",
          "scat_category": "Waste Management & Environmental Services",
          "scat_icon": "sewage.png",
          "scat_is_general": "0",
          "scat_service_area_id": "1",
          "scat_sort": "22"
        },
        {
          "svc_id": "492",
          "svc_scat_id": "28",
          "svc_description": "Hazardous Waste Management",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "28",
          "scat_category": "Waste Management & Environmental Services",
          "scat_icon": "sewage.png",
          "scat_is_general": "0",
          "scat_service_area_id": "1",
          "scat_sort": "22"
        },
        {
          "svc_id": "743",
          "svc_scat_id": "28",
          "svc_description": "Liquid Waste Evacuation",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "28",
          "scat_category": "Waste Management & Environmental Services",
          "scat_icon": "sewage.png",
          "scat_is_general": "0",
          "scat_service_area_id": "1",
          "scat_sort": "22"
        },
        {
          "svc_id": "564",
          "svc_scat_id": "28",
          "svc_description": "Refuse Collection and Disposal",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "28",
          "scat_category": "Waste Management & Environmental Services",
          "scat_icon": "sewage.png",
          "scat_is_general": "0",
          "scat_service_area_id": "1",
          "scat_sort": "22"
        },
        {
          "svc_id": "742",
          "svc_scat_id": "28",
          "svc_description": "Spillage Clean-Up",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "28",
          "scat_category": "Waste Management & Environmental Services",
          "scat_icon": "sewage.png",
          "scat_is_general": "0",
          "scat_service_area_id": "1",
          "scat_sort": "22"
        },
        {
          "svc_id": "565",
          "svc_scat_id": "28",
          "svc_description": "Waste Treatment",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "28",
          "scat_category": "Waste Management & Environmental Services",
          "scat_icon": "sewage.png",
          "scat_is_general": "0",
          "scat_service_area_id": "1",
          "scat_sort": "22"
        },
        {
          "svc_id": "363",
          "svc_scat_id": "28",
          "svc_description": "Others",
          "svc_code": "MTN-SW015",
          "svc_sort": "1",
          "scat_id": "28",
          "scat_category": "Waste Management & Environmental Services",
          "scat_icon": "sewage.png",
          "scat_is_general": "0",
          "scat_service_area_id": "1",
          "scat_sort": "22"
        },
        {
          "svc_id": "534",
          "svc_scat_id": "36",
          "svc_description": "Home Relocation Services",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "36",
          "scat_category": "Warehousing Logistics  and Relocation Services",
          "scat_icon": "warehouse.png",
          "scat_is_general": "0",
          "scat_service_area_id": "3",
          "scat_sort": "23"
        },
        {
          "svc_id": "533",
          "svc_scat_id": "36",
          "svc_description": "Logistics Services",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "36",
          "scat_category": "Warehousing Logistics  and Relocation Services",
          "scat_icon": "warehouse.png",
          "scat_is_general": "0",
          "scat_service_area_id": "3",
          "scat_sort": "23"
        },
        {
          "svc_id": "587",
          "svc_scat_id": "36",
          "svc_description": "Mailing Services",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "36",
          "scat_category": "Warehousing Logistics  and Relocation Services",
          "scat_icon": "warehouse.png",
          "scat_is_general": "0",
          "scat_service_area_id": "3",
          "scat_sort": "23"
        },
        {
          "svc_id": "537",
          "svc_scat_id": "36",
          "svc_description": "Movers",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "36",
          "scat_category": "Warehousing Logistics  and Relocation Services",
          "scat_icon": "warehouse.png",
          "scat_is_general": "0",
          "scat_service_area_id": "3",
          "scat_sort": "23"
        },
        {
          "svc_id": "535",
          "svc_scat_id": "36",
          "svc_description": "Office Relocation Services",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "36",
          "scat_category": "Warehousing Logistics  and Relocation Services",
          "scat_icon": "warehouse.png",
          "scat_is_general": "0",
          "scat_service_area_id": "3",
          "scat_sort": "23"
        },
        {
          "svc_id": "540",
          "svc_scat_id": "36",
          "svc_description": "Storage/Safe Equipment",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "36",
          "scat_category": "Warehousing Logistics  and Relocation Services",
          "scat_icon": "warehouse.png",
          "scat_is_general": "0",
          "scat_service_area_id": "3",
          "scat_sort": "23"
        },
        {
          "svc_id": "558",
          "svc_scat_id": "36",
          "svc_description": "Temporary Storage of Personal Effects",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "36",
          "scat_category": "Warehousing Logistics  and Relocation Services",
          "scat_icon": "warehouse.png",
          "scat_is_general": "0",
          "scat_service_area_id": "3",
          "scat_sort": "23"
        },
        {
          "svc_id": "536",
          "svc_scat_id": "36",
          "svc_description": "Warehousing/Storage Services",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "36",
          "scat_category": "Warehousing Logistics  and Relocation Services",
          "scat_icon": "warehouse.png",
          "scat_is_general": "0",
          "scat_service_area_id": "3",
          "scat_sort": "23"
        },
        {
          "svc_id": "541",
          "svc_scat_id": "36",
          "svc_description": "Others",
          "svc_code": null,
          "svc_sort": "1",
          "scat_id": "36",
          "scat_category": "Warehousing Logistics  and Relocation Services",
          "scat_icon": "warehouse.png",
          "scat_is_general": "0",
          "scat_service_area_id": "3",
          "scat_sort": "23"
        },
        {
          "svc_id": "673",
          "svc_scat_id": "38",
          "svc_description": "Beautician",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "38",
          "scat_category": "Home Furniture",
          "scat_icon": "1pe9uo1588009179310.png",
          "scat_is_general": "0",
          "scat_service_area_id": "2",
          "scat_sort": "24"
        },
        {
          "svc_id": "561",
          "svc_scat_id": "38",
          "svc_description": "Body Massage",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "38",
          "scat_category": "Home Furniture",
          "scat_icon": "1pe9uo1588009179310.png",
          "scat_is_general": "0",
          "scat_service_area_id": "2",
          "scat_sort": "24"
        },
        {
          "svc_id": "706",
          "svc_scat_id": "38",
          "svc_description": "Collection  and Delivery Services",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "38",
          "scat_category": "Home Furniture",
          "scat_icon": "1pe9uo1588009179310.png",
          "scat_is_general": "0",
          "scat_service_area_id": "2",
          "scat_sort": "24"
        },
        {
          "svc_id": "708",
          "svc_scat_id": "38",
          "svc_description": "Errand Services",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "38",
          "scat_category": "Home Furniture",
          "scat_icon": "1pe9uo1588009179310.png",
          "scat_is_general": "0",
          "scat_service_area_id": "2",
          "scat_sort": "24"
        },
        {
          "svc_id": "562",
          "svc_scat_id": "38",
          "svc_description": "Fitness Trainers",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "38",
          "scat_category": "Home Furniture",
          "scat_icon": "1pe9uo1588009179310.png",
          "scat_is_general": "0",
          "scat_service_area_id": "2",
          "scat_sort": "24"
        },
        {
          "svc_id": "671",
          "svc_scat_id": "38",
          "svc_description": "Gele Tiers",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "38",
          "scat_category": "Home Furniture",
          "scat_icon": "1pe9uo1588009179310.png",
          "scat_is_general": "0",
          "scat_service_area_id": "2",
          "scat_sort": "24"
        },
        {
          "svc_id": "676",
          "svc_scat_id": "38",
          "svc_description": "Home Barbing",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "38",
          "scat_category": "Home Furniture",
          "scat_icon": "1pe9uo1588009179310.png",
          "scat_is_general": "0",
          "scat_service_area_id": "2",
          "scat_sort": "24"
        },
        {
          "svc_id": "679",
          "svc_scat_id": "38",
          "svc_description": "Home Cooking",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "38",
          "scat_category": "Home Furniture",
          "scat_icon": "1pe9uo1588009179310.png",
          "scat_is_general": "0",
          "scat_service_area_id": "2",
          "scat_sort": "24"
        },
        {
          "svc_id": "674",
          "svc_scat_id": "38",
          "svc_description": "Home Doctor",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "38",
          "scat_category": "Home Furniture",
          "scat_icon": "1pe9uo1588009179310.png",
          "scat_is_general": "0",
          "scat_service_area_id": "2",
          "scat_sort": "24"
        },
        {
          "svc_id": "707",
          "svc_scat_id": "38",
          "svc_description": "Home Shopping Assistance",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "38",
          "scat_category": "Home Furniture",
          "scat_icon": "1pe9uo1588009179310.png",
          "scat_is_general": "0",
          "scat_service_area_id": "2",
          "scat_sort": "24"
        },
        {
          "svc_id": "705",
          "svc_scat_id": "38",
          "svc_description": "Home Tutor Services",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "38",
          "scat_category": "Home Furniture",
          "scat_icon": "1pe9uo1588009179310.png",
          "scat_is_general": "0",
          "scat_service_area_id": "2",
          "scat_sort": "24"
        },
        {
          "svc_id": "677",
          "svc_scat_id": "38",
          "svc_description": "House Party Services",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "38",
          "scat_category": "Home Furniture",
          "scat_icon": "1pe9uo1588009179310.png",
          "scat_is_general": "0",
          "scat_service_area_id": "2",
          "scat_sort": "24"
        },
        {
          "svc_id": "704",
          "svc_scat_id": "38",
          "svc_description": "Housekeeping",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "38",
          "scat_category": "Home Furniture",
          "scat_icon": "1pe9uo1588009179310.png",
          "scat_is_general": "0",
          "scat_service_area_id": "2",
          "scat_sort": "24"
        },
        {
          "svc_id": "675",
          "svc_scat_id": "38",
          "svc_description": "Ladies Hair Styling",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "38",
          "scat_category": "Home Furniture",
          "scat_icon": "1pe9uo1588009179310.png",
          "scat_is_general": "0",
          "scat_service_area_id": "2",
          "scat_sort": "24"
        },
        {
          "svc_id": "678",
          "svc_scat_id": "38",
          "svc_description": "Laundry Services",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "38",
          "scat_category": "Home Furniture",
          "scat_icon": "1pe9uo1588009179310.png",
          "scat_is_general": "0",
          "scat_service_area_id": "2",
          "scat_sort": "24"
        },
        {
          "svc_id": "563",
          "svc_scat_id": "38",
          "svc_description": "Manicure & Pedicure",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "38",
          "scat_category": "Home Furniture",
          "scat_icon": "1pe9uo1588009179310.png",
          "scat_is_general": "0",
          "scat_service_area_id": "2",
          "scat_sort": "24"
        },
        {
          "svc_id": "670",
          "svc_scat_id": "38",
          "svc_description": "Nursing",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "38",
          "scat_category": "Home Furniture",
          "scat_icon": "1pe9uo1588009179310.png",
          "scat_is_general": "0",
          "scat_service_area_id": "2",
          "scat_sort": "24"
        },
        {
          "svc_id": "672",
          "svc_scat_id": "38",
          "svc_description": "Personal Nutritionist",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "38",
          "scat_category": "Home Furniture",
          "scat_icon": "1pe9uo1588009179310.png",
          "scat_is_general": "0",
          "scat_service_area_id": "2",
          "scat_sort": "24"
        },
        {
          "svc_id": "554",
          "svc_scat_id": "38",
          "svc_description": "Others",
          "svc_code": null,
          "svc_sort": "1",
          "scat_id": "38",
          "scat_category": "Home Furniture",
          "scat_icon": "1pe9uo1588009179310.png",
          "scat_is_general": "0",
          "scat_service_area_id": "2",
          "scat_sort": "24"
        },
        {
          "svc_id": "711",
          "svc_scat_id": "56",
          "svc_description": "Rent Coliving Space",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "56",
          "scat_category": "Serviced Offices and Apartments",
          "scat_icon": "6fvxkn1588939913405.png",
          "scat_is_general": "0",
          "scat_service_area_id": "3",
          "scat_sort": "28"
        },
        {
          "svc_id": "698",
          "svc_scat_id": "56",
          "svc_description": "Rent Coworking Space",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "56",
          "scat_category": "Serviced Offices and Apartments",
          "scat_icon": "6fvxkn1588939913405.png",
          "scat_is_general": "0",
          "scat_service_area_id": "3",
          "scat_sort": "28"
        },
        {
          "svc_id": "712",
          "svc_scat_id": "56",
          "svc_description": "Rent Serviced Apartment",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "56",
          "scat_category": "Serviced Offices and Apartments",
          "scat_icon": "6fvxkn1588939913405.png",
          "scat_is_general": "0",
          "scat_service_area_id": "3",
          "scat_sort": "28"
        },
        {
          "svc_id": "699",
          "svc_scat_id": "57",
          "svc_description": "Inverter Power Backup System",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "57",
          "scat_category": "Renewable Energy Solutions",
          "scat_icon": "ipt8q1600059586337.png",
          "scat_is_general": "0",
          "scat_service_area_id": "1",
          "scat_sort": "28"
        },
        {
          "svc_id": "709",
          "svc_scat_id": "57",
          "svc_description": "Solar Power Backup System",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "57",
          "scat_category": "Renewable Energy Solutions",
          "scat_icon": "ipt8q1600059586337.png",
          "scat_is_general": "0",
          "scat_service_area_id": "1",
          "scat_sort": "28"
        },
        {
          "svc_id": "710",
          "svc_scat_id": "57",
          "svc_description": "Wind Turbine System",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "57",
          "scat_category": "Renewable Energy Solutions",
          "scat_icon": "ipt8q1600059586337.png",
          "scat_is_general": "0",
          "scat_service_area_id": "1",
          "scat_sort": "28"
        },
        {
          "svc_id": "729",
          "svc_scat_id": "61",
          "svc_description": "Pickup and Delivery",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "61",
          "scat_category": "Pickup & Delivery",
          "scat_icon": "q6wcfq1606121332084.png",
          "scat_is_general": "0",
          "scat_service_area_id": "3",
          "scat_sort": "28"
        },
        {
          "svc_id": "738",
          "svc_scat_id": "65",
          "svc_description": "Monthly Routine",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "65",
          "scat_category": "Facility Inspection Service",
          "scat_icon": "2ono61644407950594.PNG",
          "scat_is_general": "0",
          "scat_service_area_id": "1",
          "scat_sort": "29"
        },
        {
          "svc_id": "740",
          "svc_scat_id": "65",
          "svc_description": "One-Off",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "65",
          "scat_category": "Facility Inspection Service",
          "scat_icon": "2ono61644407950594.PNG",
          "scat_is_general": "0",
          "scat_service_area_id": "1",
          "scat_sort": "29"
        },
        {
          "svc_id": "739",
          "svc_scat_id": "65",
          "svc_description": "Quarterly Routine",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "65",
          "scat_category": "Facility Inspection Service",
          "scat_icon": "2ono61644407950594.PNG",
          "scat_is_general": "0",
          "scat_service_area_id": "1",
          "scat_sort": "29"
        },
        {
          "svc_id": "737",
          "svc_scat_id": "65",
          "svc_description": "Weekly Routine",
          "svc_code": null,
          "svc_sort": "0",
          "scat_id": "65",
          "scat_category": "Facility Inspection Service",
          "scat_icon": "2ono61644407950594.PNG",
          "scat_is_general": "0",
          "scat_service_area_id": "1",
          "scat_sort": "29"
        }
    ]', true);

    $allServices = [];

    foreach ($categories as $category) {
        $scat_id = $category['scat_id'];
        $allServices[] = [
            "scat_category" => $category['scat_category'],
            "service_name" => $category['svc_description'],
            "service_slug" => \Str::slug($category['svc_description']),
        ];
    }

    // Return all services
    return response()->json($allServices);

});


Route::middleware(['auth:sanctum'])->domain(env('APP_URL'))->group(function () {
    Route::get('/', function () {
        return view('welcome');
    });
});


Route::middleware('admin')->group(function () {
    require_once('admin.php');
});


Route::fallback(function () {
    return get_error_response("API resource not found", [
        "error" => "API resource not found"
    ], 404);
});

// Route::prefix('admin')->name('admin.')->group(function () {
//     Route::resource('service_areas', ServiceAreaController::class);
// });


Route::get('/chat/{friend}', function (User $friend) {
    return view('chat', [
        'friend' => $friend
    ]);
})->middleware(['auth:sanctum'])->name('chat');


Route::post('/messages/{friend}', function (User $friend) {
    $message = ChatMessage::create([
        'sender_id' => auth()->id(),
        'receiver_id' => $friend->id,
        'text' => request()->input('message')
    ]);

    broadcast(new MessageSent($message));

    return $message;
})->middleware(['auth:sanctum']);

Route::get('/messages/{friend}', function (User $friend) {
    return ChatMessage::query()
        ->where(function ($query) use ($friend) {
            $query->where('sender_id', auth()->id())
                ->where('receiver_id', $friend->id);
        })
        ->orWhere(function ($query) use ($friend) {
            $query->where('sender_id', $friend->id)
                ->where('receiver_id', auth()->id());
        })
        ->with(['sender', 'receiver'])
        ->orderBy('id', 'asc')
        ->get();
})->middleware(['auth:sanctum']);


Route::withoutMiddleware(VerifyCsrfToken::class)->group(function () {
    Route::any('webhook/callback/paystack', [WebhookLogController::class, 'handleWebhook']);
});
