name: Deploy call2fix 2 cPanel
on:
  push:
    branches:
      - main
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 0
    steps:
      - name: Get the latest code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Install Composer Dependencies
        run: composer install --ignore-platform-reqs --no-dev

      - name: Generate key
        run: php artisan key:generate

      - name: Generate storage link
        run: php artisan storage:link

      - name: Migrate Database
        run: php artisan migrate:fresh --seed --force 

      - name: Create ZIP file
        run: zip -r release.zip . -x "**/.git*" "**/.git*/**" "**/node_modules/**"

      - name: Upload ZIP file via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftp.woju.com.ng
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /
          local-dir: ./