name: 🚀 Deploy website on push

on:
  push:
    branches:
      - main  # or your default branch name

jobs:
    web-deploy:
        name: 🎉 Deploy

        runs-on: ubuntu-latest
        steps:
            - name: 🚚 Get latest code
              uses: actions/checkout@v3
            - name: Prepare the environment
              run: cp .env.example .env
            - name: Run composer install
              run: |
                    composer validate && composer install --ignore-platform-reqs --prefer-dist
            - name: 📂 Sync files
              uses: SamKirkland/FTP-Deploy-Action@v4.3.4
              with:
                    server-dir: /
                    server: ${{ secrets.FTP_SERVER}}
                    username: ${{ secrets.FTP_USERNAME }}
                    password: ${{ secrets.FTP_PASSWORD }}
                    exclude: |
                        .env
                        .git*
                        .github/
                        node_modules/
                        vendor/
                        storage/logs/*.log
                        tests/
                        .editorconfig
                        .gitattributes
                        .gitignore
                        .styleci.yml
                        README.md
                        phpunit.xml

                                